# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Pf03uTE3HTG878GcLcSKDcH2dsGagwX
"""

!pip install torch transformers datasets torchaudio

import zipfile
import os
import pandas as pd
# Unzip training set
local_zip = '/content/arabic.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('wav')

import os
import librosa
from datasets import Dataset
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Paths to the directories containing your files
audio_dir = "/content/wav/arabic-speech-corpus/wav"
text_dir = "/content/wav/arabic-speech-corpus/lab"  # Assuming 'lab' contains transcription text

# Function to load and preprocess the audio
def preprocess_audio(audio_path):
    audio, sr = librosa.load(audio_path, sr=None)  # Load audio with original sample rate
    # Extract MFCCs (Mel-frequency cepstral coefficients) as features
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)  # Corrected to use keyword arguments
    mfcc = np.mean(mfcc.T, axis=0)  # Averaging over time axis (frames)
    return mfcc

# Function to load and preprocess the text (from 'lab' files)
def preprocess_text(text_path):
    with open(text_path, 'r') as file:
        text = file.read().strip()  # Read and clean the text
    return text

# Create a list of dictionaries containing the processed data
data = []
for file_name in os.listdir(audio_dir):
    if file_name.endswith(".wav"):  # Check if it's a wav file
        # Get the corresponding 'lab' file (assuming same name without extension)
        base_name = os.path.splitext(file_name)[0]
        text_file = os.path.join(text_dir, f"{base_name}.lab")  # lab file with transcription

        if os.path.exists(text_file):
            # Preprocess audio and text
            audio_features = preprocess_audio(os.path.join(audio_dir, file_name))
            text = preprocess_text(text_file)

            # Add to the data list
            data.append({'audio': audio_features, 'text': text})

# Create the dataset from the processed data
dataset = Dataset.from_dict({"audio": [entry['audio'] for entry in data], "text": [entry['text'] for entry in data]})

# Optionally encode the text labels (if needed for classification tasks)
label_encoder = LabelEncoder()
dataset = dataset.map(lambda x: {'text': label_encoder.fit_transform([x['text']])[0]})

# Print out the first entry in the dataset
print(dataset[0])  # Show the first example

from sklearn.model_selection import train_test_split

# Split the dataset into training and validation sets
train_data, val_data = train_test_split(data, test_size=0.2, random_state=42)

# Optionally create datasets from the split data
train_dataset = Dataset.from_dict({"audio": [entry['audio'] for entry in train_data], "text": [entry['text'] for entry in train_data]})
val_dataset = Dataset.from_dict({"audio": [entry['audio'] for entry in val_data], "text": [entry['text'] for entry in val_data]})

import torch
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import LabelEncoder

# Convert the data to PyTorch tensors
audio_data = np.array([entry['audio'] for entry in data])
text_labels = np.array([entry['text'] for entry in data])

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform text labels to numerical representation
text_labels_encoded = label_encoder.fit_transform(text_labels)

# Create TensorDataset using encoded text labels
dataset = TensorDataset(torch.tensor(audio_data, dtype=torch.float32),
                        torch.tensor(text_labels_encoded, dtype=torch.long))

# Create DataLoader
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# Example of iterating over the dataloader
for batch in dataloader:
    audio_batch, text_batch = batch
    print(audio_batch.shape, text_batch.shape)  # Check the batch shapes

import torch
import torch.nn as nn
import torch.optim as optim

class SpeechRecognitionModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SpeechRecognitionModel, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.softmax = nn.Softmax(dim=1)  # For classification

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.softmax(x)  # Return probabilities for classification
        return x

# Define model hyperparameters
input_dim = 13  # 13 MFCC features
hidden_dim = 64  # Hidden layer size
output_dim = len(label_encoder.classes_)  # Number of classes in your text labels

# Create model instance
model = SpeechRecognitionModel(input_dim, hidden_dim, output_dim)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()  # Suitable for multi-class classification
optimizer = optim.Adam(model.parameters(), lr=0.001)

import torch
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Check if GPU is available and use it; otherwise, fall back to CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Ensure text_data has the correct shape and type
text_labels = np.array([entry['text'] for entry in data])  # Extract text labels from your data

# Initialize and fit LabelEncoder if not already done
label_encoder = LabelEncoder()
label_encoder.fit(text_labels)  # Fit on all unique labels

# Transform text labels to numerical representation
text_data_encoded = label_encoder.transform(text_labels)

# Convert encoded labels to PyTorch tensor with correct type
text_data = torch.tensor(text_data_encoded, dtype=torch.long)

# Assuming audio_data is already available as a tensor
# Convert audio_data to PyTorch tensor if it's not already done
audio_data = torch.tensor(audio_data, dtype=torch.float32)

# Create a TensorDataset and DataLoader
dataset = TensorDataset(audio_data, text_data)
train_loader = DataLoader(dataset, batch_size=16, shuffle=True)

# Move model to the correct device
model.to(device)

# Training loop
epochs = 10
batch_size = 16

for epoch in range(epochs):
    model.train()  # Set the model to training mode
    running_loss = 0.0

    # Loop through batches
    for audio_batch, text_batch in train_loader:
        # Move batches to the correct device (GPU or CPU)
        audio_batch = audio_batch.to(device)
        text_batch = text_batch.to(device)

        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass: Get predictions from the model
        outputs = model(audio_batch)

        # Calculate the loss
        loss = criterion(outputs, text_batch)

        # Backward pass: Calculate gradients
        loss.backward()

        # Update the model weights
        optimizer.step()

        # Update running loss
        running_loss += loss.item()

    # Print statistics every epoch
    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader)}")

# After training, save the model if desired
torch.save(model.state_dict(), "speech_recognition_model.pth")

!pip install tensorflow librosa

import zipfile
import os
import numpy as np
import librosa
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split

# Unzip the training set
local_zip = '/content/arabic.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('wav')

# Paths to the directories containing your files
audio_dir = "/content/wav/arabic-speech-corpus/wav"
text_dir = "/content/wav/arabic-speech-corpus/lab"  # Assuming 'lab' contains transcription text

import librosa
import numpy as np

# Function to load and preprocess both audio and text
def preprocess_audio_and_text(audio_path, text_path):
    # Load and preprocess the audio
    audio, sr = librosa.load(audio_path, sr=None)  # Load audio with original sample rate
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)  # Extract 13 MFCC features
    mfcc_delta = librosa.feature.delta(mfcc)  # First order delta (derivative)
    mfcc_delta2 = librosa.feature.delta(mfcc, order=2)  # Second order delta (second derivative)
    mfcc_features = np.concatenate([mfcc, mfcc_delta, mfcc_delta2], axis=0)  # Concatenate MFCCs with deltas
    mfcc_features = np.mean(mfcc_features.T, axis=0)  # Average over time frames

    # Load and preprocess the text
    with open(text_path, 'r') as file:
        text = file.read().strip()  # Read and clean the text

    return mfcc_features, text  # Return both audio and text features

data = []
for file_name in os.listdir(audio_dir):
    if file_name.endswith(".wav"):  # Check if it's a wav file
        # Get the corresponding 'lab' file (assuming same name without extension)
        base_name = os.path.splitext(file_name)[0]
        text_file = os.path.join(text_dir, f"{base_name}.lab")  # lab file with transcription

        if os.path.exists(text_file):
            # Preprocess audio and text
            audio_features = preprocess_audio(os.path.join(audio_dir, file_name))
            text = preprocess_text(text_file)

            # Add to the data list
            data.append({'audio': audio_features, 'text': text})

# Create a pandas dataframe
df = pd.DataFrame(data)

# Encode the text labels (if needed for classification tasks)
label_encoder = LabelEncoder()
df['text_encoded'] = label_encoder.fit_transform(df['text'])

# Split the dataset into training and validation sets
train_data, val_data = train_test_split(df, test_size=0.2, random_state=42)

# Convert to numpy arrays
X_train = np.array(train_data['audio'].tolist())  # Convert list of audio features to numpy array
y_train = np.array(train_data['text_encoded'])

X_val = np.array(val_data['audio'].tolist())  # Convert list of audio features to numpy array
y_val = np.array(val_data['text_encoded'])

# Reshape X_train and X_val for LSTM input (add a sequence dimension)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_val = X_val.reshape((X_val.shape[0], X_val.shape[1], 1))

# Simplified model architecture
model = models.Sequential()

# Add a single LSTM layer
model.add(layers.LSTM(128, input_shape=(X_train.shape[1], 1)))

# Add a Dense layer and output layer
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(len(label_encoder.classes_), activation='softmax'))  # Output layer for classification

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Summary of the model architecture
model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32)

model.save("speech_recognition_model_tf.h5")